# -*- coding: utf-8 -*-
"""YOLO12n.pt: POTHOLE DETECTION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUdIa2rkUF6EEo67x3K8fHdxtniuzGGE
"""

Data: https://app.roboflow.com/xiao-qingqing/yolo11-pothole-detection/1/export

! pip install ultralytics

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import Image

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="GDvL95GhiPJR9AxYDwRq")
project = rf.workspace("xiao-qingqing").project("potholes-detection-98sn7")
version = project.version(3)
dataset = version.download("yolov12")

dataset.location

!yolo task=detect mode=train model=yolo12n.pt data='/content/POTHOLES-DETECTION-3/data.yaml' epochs=100 imgsz=640

from IPython.display import Image

Image("/content/runs/detect/train/confusion_matrix.png", width=600)

Image("/content/runs/detect/train/labels.jpg", width=600)

Image("/content/runs/detect/train/results.png", width=600)

Image("/content/runs/detect/train/train_batch0.jpg", width=600)

Image("/content/runs/detect/train/val_batch0_pred.jpg", width=600)

Image("/content/runs/detect/train/val_batch0_pred.jpg", width=600)

!yolo task=detect mode=val model="/content/runs/detect/train/weights/best.pt" data={dataset.location}/data.yaml

!yolo task=detect mode=predict model="/content/runs/detect/train/weights/best.pt" conf=0.25 source={dataset.location}/test/images save=True

import glob
import os
from IPython.display import Image as IPyImage, display
latest_folder = max(glob.glob('/content/runs/detect/predict*/'), key=os.path.getmtime)
for img in glob.glob(f'{latest_folder}/*.jpg')[1:4]:
    display(IPyImage(filename=img, width=600))
    print("\n")