# -*- coding: utf-8 -*-
"""Tomato Segmentation_YOLOv12m

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3E6vDJtLbTiNMOU8nLNMhbFn26pisHx
"""

! pip install ultralytics

from IPython.display import Image

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/ultralytics/ultralytics/yolo/12/segment

!pwd

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="GDvL95GhiPJR9AxYDwRq")
project = rf.workspace("xiao-qingqing").project("tomato-segmentation-hyz4e")
version = project.version(4)
dataset = version.download("yolov12")

dataset.location

!yolo task=segment mode=train model=yolo12m-seg.yaml data='/content/TOMATO-SEGMENTATION-4/data.yaml' epochs=150 imgsz=640 device=0 batch=16 optimizer=auto patience=50 momentum=0.9 weight_decay=0.0005 workers=8

from IPython.display import Image

Image("/content/runs/segment/train/confusion_matrix.png", width=600)

Image("/content/runs/segment/train/labels.jpg", width=600)

Image("/content/runs/segment/train/results.png", width=600)

Image("/content/runs/segment/train/train_batch0.jpg", width=600)

Image("/content/runs/segment/train/val_batch0_pred.jpg", width=600)

Image("/content/runs/segment/train/val_batch0_pred.jpg", width=600)

!yolo task=segment mode=val model="/content/runs/segment/train/weights/best.pt" data={dataset.location}/data.yaml

import glob
import os
from IPython.display import Image as IPyImage, display

# Check if any 'predict' folders exist, and if not, use the 'train2' folder
predict_folders = glob.glob('/content/runs/segment/train*/')
if not predict_folders:
    print("No 'predict' folders found. Using 'train2' folder instead.")
    latest_folder = '/content/runs/segment/train2/'  # Fallback to 'train2'
else:
    latest_folder = max(predict_folders, key=os.path.getmtime)

for img in glob.glob(f'{latest_folder}/*.jpg')[1:4]:
    display(IPyImage(filename=img, width=600))
    print("\n")